name: dog_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: 5.4.0
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  freezed_annotation: 2.4.1
  go_router: ^13.0.0
  http: ^1.1.2
  json_annotation: 4.8.1
  path_provider: ^2.1.1
  retrofit: 4.0.3
  svg_flutter: ^0.0.1

dev_dependencies:
  build_runner: 2.4.7
  flutter_gen_runner: 5.3.2
  flutter_test:
    sdk: flutter

  freezed: 2.4.6
  json_serializable: 6.7.1
  retrofit_generator: 7.0.6
  very_good_analysis: 5.1.0

flutter:
  fonts:
    - family: Galano Grotesque
      fonts:
        - asset: assets/fonts/GalanoGrotesqueRegular.otf
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
